const API='https://rfwiykhpewixomoargkf.supabase.co/rest/v1/japan_tsmc_items';
const KEY='sb_publishable_bccQGMlsYmvxWpK3UApBKw_iVRvba-l';
const categories=['餐廳','酒吧','景點','購物','住宿','交通','其他'];
const days=Array.from({length:7},(_,i)=>`2027-01-${10+i}`);
const weekdays=['日','一','二','三','四','五','六'];
let items=[],view='list',editing=null,busy=false,loading=false,loaded=false,selectedDay=days[0];
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeLink(link){try{const u=new URL(link);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
async function request(query='',method='GET',body){const res=await fetch(API+query,{method,headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000),cache:'no-store'});if(!res.ok)throw new Error('連線失敗，請稍後再試。');return res.status===204?[]:res.json()}
async function sync(){if(loading||busy)return;loading=true;try{items=await request('?select=*&order=created_at.asc');loaded=true;$('#status').textContent='';render()}catch(e){$('#status').textContent='同步失敗，請重試';if(!loaded)$('#content').innerHTML='<p class="empty">暫時無法讀取清單。<button class="retry" id="retry">重新連線</button></p>'}finally{loading=false}}
function card(item){const link=safeLink(item.link);return `<article class="card"><div class="card-top"><h3>${escapeHTML(item.title)}</h3><button class="edit" data-id="${item.id}" aria-label="編輯 ${escapeHTML(item.title)}">編輯</button></div>${item.area?`<p class="meta">${escapeHTML(item.area)}</p>`:''}${item.note?`<p class="note">${escapeHTML(item.note)}</p>`:''}<div class="card-bottom">${link?`<a href="${escapeHTML(link)}" target="_blank" rel="noopener noreferrer">${item.category==='住宿'?'查看住宿':'開啟連結'}</a>`:'<span></span>'}${item.category==='餐廳'&&item.meal?`<span class="meal-tag">${escapeHTML(item.meal)}</span>`:''}${item.day?`<span class="badge">1/${Number(item.day.slice(-2))}${item.at_time?' · '+escapeHTML(item.at_time.slice(0,5)):''}</span>`:'<span class="meta">待安排</span>'}</div></article>`}
const symbols={'餐廳':'🍽','酒吧':'🍸','景點':'⌖','購物':'▧','住宿':'⌂','交通':'⇄','其他':'⋯'};
function group(title,rows,empty,category=title,context=''){return `<section class="group category-${categories.indexOf(category)}"><div class="group-head"><div class="group-label"><span class="category-icon" aria-hidden="true">${symbols[category]||''}</span><h2>${escapeHTML(title)}</h2><span class="count">${rows.length}</span></div><button class="group-add" data-add="${escapeHTML(category)}" data-meal="${escapeHTML(context)}" aria-label="新增${escapeHTML(title)}">＋</button></div>${rows.length?'<div class="cards">'+rows.map(card).join('')+'</div>':`<p class="empty">${empty}</p>`}</section>`}
function render(){if(!loaded)return;let html='';if(view==='list'){html='<div class="category-grid">';for(const column of [['餐廳','景點','其他'],['酒吧','購物','交通']]){html+='<div class="category-stack">';for(const cat of column)html+=group(cat,items.filter(x=>x.category===cat),'尚未加入');html+='</div>'}html+='</div>'}else if(view==='plan'){html='<div class="day-tabs" aria-label="行程日期">'+days.map((d,i)=>`<button data-day="${d}" aria-pressed="${selectedDay===d}"><span>DAY ${i+1}</span><strong>1/${10+i}</strong><small>${weekdays[i]}</small></button>`).join('')+'</div>';const rows=items.filter(x=>x.day===selectedDay).sort((a,b)=>(a.at_time||'99').localeCompare(b.at_time||'99'));html+='<div class="category-grid daily-grid">';html+=group('景點',rows.filter(x=>x.category==='景點'),'尚未安排');html+='<section class="group meal-group"><div class="group-head"><div class="group-label"><span class="category-icon" aria-hidden="true">🍽</span><h2>餐廳</h2><span class="count">'+rows.filter(x=>x.category==='餐廳').length+'</span></div><button class="group-add" data-add="餐廳" aria-label="新增餐廳">＋</button></div>';for(const meal of ['早餐','午餐','晚餐','其他時段','未定']){const mealRows=rows.filter(x=>x.category==='餐廳'&&(x.meal||'未定')===meal);if(meal==='未定'&&!mealRows.length)continue;html+='<div class="meal-section"><div class="meal-heading"><h3>'+meal+'</h3><button class="group-add" data-add="餐廳" data-meal="'+(meal==='未定'?'':meal)+'" aria-label="新增'+meal+'">＋</button></div>'+(mealRows.length?'<div class="cards">'+mealRows.map(card).join('')+'</div>':'<p class="empty">尚未安排</p>')+'</div>'}html+='</section>';for(const cat of ['交通','購物','酒吧','住宿','其他']){const subset=rows.filter(x=>x.category===cat);if(cat==='其他'&&!subset.length)continue;html+=group(cat,subset,'尚未安排')}html+='</div>'}else{html='<div class="stay-grid">';for(const period of ['1/10–1/12','1/12–1/13','1/13–1/16'])html+=group(period,items.filter(x=>x.category==='住宿'&&x.area===period),'尚未加入','住宿');const others=items.filter(x=>x.category==='住宿'&&!['1/10–1/12','1/12–1/13','1/13–1/16'].includes(x.area));if(others.length)html+=group('其他住宿',others,'','住宿');html+='</div>'}$('#content').innerHTML=html}
function openEditor(item=null,category=null,meal=""){editing=item?{...item}:null;$('#form').reset();$('#form-error').textContent='';$('#form-title').textContent=item?'編輯地方':'新增想去的地方';$('#remove').hidden=!item;for(const field of ['title','category','area','link','note','day','at_time','meal'])if(item)$('#form').elements[field].value=item[field]||'';if(!item&&view==='stay')$('#form').elements.category.value='住宿';if(!item&&category)$('#form').elements.category.value=category;if(!item&&meal)$('#form').elements.meal.value=meal;if(!item&&view==='plan')$('#form').elements.day.value=selectedDay;updateMealField();$('#editor').showModal();$('#form').elements.title.focus()}
function updateMealField(){$('#meal-field').hidden=$('#form').elements.category.value!=='餐廳'}
$('#form').elements.category.onchange=updateMealField;
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));render()});
$('#content').onclick=e=>{const b=e.target.closest('[data-id]');if(b)openEditor(items.find(x=>x.id===b.dataset.id));const add=e.target.closest('[data-add]');if(add)openEditor(null,add.dataset.add,add.dataset.meal||'');const day=e.target.closest('[data-day]');if(day){selectedDay=day.dataset.day;render()}if(e.target.id==='retry')sync()};
function setBusy(state){busy=state;$('#save').disabled=state;$('#remove').disabled=state;$('#close').disabled=state;$('#save').textContent=state?'儲存中…':'儲存'}
$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault()});
$('#form').onsubmit=async e=>{e.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(e.target));for(const k of Object.keys(data))data[k]=data[k].trim();if(!data.title){$('#form-error').textContent='請填寫名稱。';return}if(data.link&&!safeLink(data.link)){$('#form-error').textContent='請使用 http 或 https 連結。';return}if(data.category!=='餐廳')data.meal='';data.day=data.day||null;data.at_time=data.at_time||null;data.revision=(editing?.revision||0)+1;setBusy(true);$('#form-error').textContent='';try{const rows=await request(editing?`?id=eq.${editing.id}&revision=eq.${editing.revision}`:'',editing?'PATCH':'POST',data);if(!rows.length)throw new Error('這筆資料剛被朋友修改了。請關閉後重開編輯，避免蓋掉新內容。');$('#editor').close()}catch(err){$('#form-error').textContent=err.message}finally{setBusy(false);await sync()}};
$('#remove').onclick=async()=>{if(!editing||busy||!confirm(`確定刪除「${editing.title}」？`))return;setBusy(true);try{const rows=await request(`?id=eq.${editing.id}&revision=eq.${editing.revision}`,'DELETE');if(!rows.length)throw new Error('這筆資料已被修改，請關閉後重新確認。');$('#editor').close()}catch(err){$('#form-error').textContent=err.message}finally{setBusy(false);await sync()}};
sync();setInterval(()=>{if(!document.hidden)sync()},10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
