const API='https://rfwiykhpewixomoargkf.supabase.co/rest/v1/japan_tsmc_items';
const KEY='sb_publishable_bccQGMlsYmvxWpK3UApBKw_iVRvba-l';
const categories=['餐廳','景點','住宿','待辦','航班'],people=['Sam','家賢','沛霖','子穎'];
const days=Array.from({length:7},(_,i)=>`2027-01-${10+i}`),weekdays=['日','一','二','三','四','五','六'];
let items=[],view='list',editing=null,busy=false,loading=false,loaded=false,selectedDay=days[0],person='';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const saved=localStorage.getItem('japan_tsmc_person');if(people.includes(saved))person=saved}catch{}
function safeLink(link){try{const u=new URL(link);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
async function request(query='',method='GET',body){const res=await fetch(API+query,{method,headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000),cache:'no-store'});if(!res.ok)throw new Error('連線失敗，請稍後再試。');return res.status===204?[]:res.json()}
async function sync(){if(loading||busy)return;loading=true;try{items=await request('?select=*&archived=eq.false&order=created_at.asc');loaded=true;$('#status').textContent='';render()}catch(e){$('#status').textContent='同步失敗，請重試';if(!loaded)$('#content').innerHTML='<p class="empty">暫時無法讀取清單。<button class="retry" id="retry">重新連線</button></p>'}finally{loading=false}}
const textOrder=new Intl.Collator('zh-Hant-TW',{numeric:true,sensitivity:'base'});
function nameOrder(a,b){return textOrder.compare(a.title,b.title)||a.id.localeCompare(b.id)}
function listOrder(a,b){return Number(Boolean(a.day))-Number(Boolean(b.day))||nameOrder(a,b)}
function card(item){const link=safeLink(item.link),stamp=item.edited_by?`<p class="edit-credit">${esc(item.edited_by)} 編輯${item.updated_at?' · '+esc(new Date(item.updated_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})):''}</p>`:'';return `<article class="card${view==='list'&&['餐廳','景點'].includes(item.category)&&item.day?' scheduled-card':''}"><div class="card-top"><h3>${item.category==='待辦'?`<input class="task-check" type="checkbox" data-task="${item.id}" ${item.done?'checked':''} aria-label="完成 ${esc(item.title)}">`: ''}<span class="${item.category==='待辦'&&item.done?'task-done':''}">${esc(item.title)}</span>${item.kind?`<span class="kind-tag kind-${item.kind==='購物'?'shop':'bar'}">${esc(item.kind)}</span>`:''}</h3><button class="edit" data-id="${item.id}" aria-label="編輯 ${esc(item.title)}">編輯</button></div><div class="card-bottom">${link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${item.category==='住宿'?'查看住宿':'開啟連結'}</a>`:'<span></span>'}${item.category==='餐廳'&&item.meal?`<span class="meal-tag">${esc(item.meal==='其他時段'?'點心／宵夜':item.meal)}</span>`:''}${item.day?`<span class="badge">1/${Number(item.day.slice(-2))}${item.at_time?' · '+esc(item.at_time.slice(0,5)):''}</span>`:`<span class="meta">${item.category==='待辦'?(item.done?'已完成':'待完成'):'待安排'}</span>`}</div>${item.note?`<p class="note">${esc(item.note)}</p>`:''}${stamp}${view==='list'&&item.category!=='航班'&&item.day?`<button class="return-list" data-return="${item.id}" aria-label="返回清單 ${esc(item.title)}">返回清單</button>`:''}</article>`}
const symbols={'餐廳':'🍽','景點':'⌖','住宿':'⌂','待辦':'☑','航班':'✈'};
function group(title,rows,empty,category=title){const sorted=[...rows].sort(view==='list'?listOrder:category==='待辦'?((a,b)=>Number(a.done)-Number(b.done)||nameOrder(a,b)):view==='plan'?((a,b)=>(a.at_time||'99').localeCompare(b.at_time||'99')||nameOrder(a,b)):nameOrder);let content='';let scheduled=false;for(const row of sorted){if(view==='list'&&row.day&&!scheduled){content+='<div class="scheduled-label">已安排</div>';scheduled=true}content+=card(row)}return `<section class="group type-${category==='餐廳'?'food':category==='景點'?'place':'stay'}"><div class="group-head"><div class="group-label"><span class="category-icon" aria-hidden="true">${symbols[category]||''}</span><h2>${esc(title)}</h2><span class="count">${rows.length}</span></div><button class="group-add" data-add="${esc(category)}" aria-label="新增${esc(title)}">＋</button></div>${rows.length?'<div class="cards">'+content+'</div>':`<p class="empty">${empty}</p>`}</section>`}
function render(){if(!loaded)return;$('#flights').innerHTML=items.filter(x=>x.category==='航班').sort((a,b)=>(a.day||'').localeCompare(b.day||'')||nameOrder(a,b)).map(card).join('');let html='';if(view==='list'){html='<div class="category-grid">';for(const cat of ['餐廳','景點'])html+=group(cat,items.filter(x=>x.category===cat),'尚未加入');html+='</div>'}else if(view==='plan'){html='<div class="day-tabs" aria-label="行程日期">'+days.map((d,i)=>`<button data-day="${d}" aria-pressed="${selectedDay===d}"><span>DAY ${i+1}</span><strong>1/${10+i}</strong><small>${weekdays[i]}</small></button>`).join('')+'</div>';const rows=items.filter(x=>x.day===selectedDay).sort((a,b)=>(a.at_time||'99').localeCompare(b.at_time||'99'));if(rows.some(x=>x.category==='航班'))html+=group('航班',rows.filter(x=>x.category==='航班'),'');html+='<div class="category-grid daily-grid">';html+=group('景點',rows.filter(x=>x.category==='景點'),'尚未安排');html+='<section class="group meal-group type-food"><div class="group-head"><div class="group-label"><span class="category-icon" aria-hidden="true">🍽</span><h2>餐廳</h2><span class="count">'+rows.filter(x=>x.category==='餐廳').length+'</span></div><button class="group-add" data-add="餐廳" aria-label="新增餐廳">＋</button></div>';for(const meal of ['早餐','午餐','晚餐','其他時段','酒吧','未定']){const mealRows=rows.filter(x=>x.category==='餐廳'&&(x.kind==='酒吧'?'酒吧':x.meal||'未定')===meal);if(['其他時段','未定'].includes(meal)&&!mealRows.length)continue;html+='<div class="meal-section"><div class="meal-heading"><h3>'+(meal==='其他時段'?'點心／宵夜':meal)+'</h3><button class="group-add" data-add="餐廳" data-kind="'+(meal==='酒吧'?'酒吧':'')+'" data-meal="'+(['酒吧','未定'].includes(meal)?'':meal)+'" aria-label="新增'+(meal==='其他時段'?'點心／宵夜':meal)+'">＋</button></div>'+(mealRows.length?'<div class="cards">'+mealRows.map(card).join('')+'</div>':'<p class="empty">尚未安排</p>')+'</div>'}html+='</section>';html+=group('住宿',rows.filter(x=>x.category==='住宿'),'尚未安排');html+='</div>'}else if(view==='todo'){html=group('待辦事項',items.filter(x=>x.category==='待辦'),'新增第一個待辦事項','待辦')}else{html='<div class="stay-grid">';for(const period of ['1/10–1/12','1/12–1/13','1/13–1/16'])html+=group(period,items.filter(x=>x.category==='住宿'&&x.area===period),'尚未加入','住宿');const extra=items.filter(x=>x.category==='住宿'&&!['1/10–1/12','1/12–1/13','1/13–1/16'].includes(x.area));if(extra.length)html+=group('住宿候選',extra,'','住宿');html+='</div>'}$('#content').innerHTML=html}
function updateFields(kind=''){const category=$('#form').elements.category.value;$('#kind-field').hidden=!['餐廳','景點'].includes(category);const options=category==='景點'?[['','景點'],['購物','購物']]:[['','餐廳'],['酒吧','酒吧']];$('#form').elements.kind.innerHTML=options.map(([value,label])=>`<option value="${value}">${label}</option>`).join('');$('#form').elements.kind.value=options.some(x=>x[0]===kind)?kind:'';updateMealField()}
function updateMealField(){$('#meal-field').hidden=$('#form').elements.category.value!=='餐廳'||$('#form').elements.kind.value==='酒吧'}
function openEditor(item=null,category=null,meal='',kind=''){if(!person){$('#identity-dialog').showModal();return}editing=item?{...item}:null;$('#form').reset();$('#form-error').textContent='';$('#form-title').textContent=item?'編輯':'新增';$('#remove').hidden=!item;for(const field of ['title','category','link','note','day','at_time','meal'])if(item)$('#form').elements[field].value=item[field]||'';if(!item&&view==='todo')$('#form').elements.category.value='待辦';if(!item&&view==='stay')$('#form').elements.category.value='住宿';if(!item&&category)$('#form').elements.category.value=category;if(!item&&meal)$('#form').elements.meal.value=meal;if(!item&&view==='plan')$('#form').elements.day.value=selectedDay;updateFields(item?.kind||kind);$('#editor').showModal();$('#form').elements.title.focus()}
$('#form').elements.category.onchange=()=>updateFields();$('#form').elements.kind.onchange=updateMealField;
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));render()});
async function changeItem(item,patch){if(!item||busy)return;if(!person){$('#identity-dialog').showModal();return}setBusy(true);let error='';try{const rows=await request(`?id=eq.${item.id}&revision=eq.${item.revision}`,'PATCH',{...patch,edited_by:person,revision:item.revision+1});if(!rows.length)throw new Error('朋友剛修改了這筆資料，請重試。')}catch(e){error=e.message}finally{setBusy(false);await sync();if(error)$('#status').textContent=error}}
function handleContent(e){const task=e.target.closest('[data-task]');if(task){changeItem(items.find(x=>x.id===task.dataset.task),{done:task.checked});return}const ret=e.target.closest('[data-return]');if(ret){changeItem(items.find(x=>x.id===ret.dataset.return),{day:null,at_time:null});return}const b=e.target.closest('[data-id]');if(b)openEditor(items.find(x=>x.id===b.dataset.id));const add=e.target.closest('[data-add]');if(add)openEditor(null,add.dataset.add,add.dataset.meal||'',add.dataset.kind||'');const day=e.target.closest('[data-day]');if(day){selectedDay=day.dataset.day;render()}if(e.target.id==='retry')sync()}
$('#content').onclick=handleContent;$('#flights').onclick=handleContent;
function setBusy(state){busy=state;$('#save').disabled=state;$('#remove').disabled=state;$('#close').disabled=state;$('#save').textContent=state?'儲存中…':'儲存'}
$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault()});
$('#form').onsubmit=async e=>{e.preventDefault();if(busy||!people.includes(person))return;const data=Object.fromEntries(new FormData(e.target));for(const k of Object.keys(data))data[k]=data[k].trim();if(!data.title){$('#form-error').textContent='請填寫名稱。';return}if(data.link&&!safeLink(data.link)){$('#form-error').textContent='請使用 http 或 https 連結。';return}if(!['餐廳','景點'].includes(data.category))data.kind='';if(data.category!=='餐廳'||data.kind==='酒吧')data.meal='';data.day=data.day||null;data.at_time=data.at_time||null;data.edited_by=person;data.revision=(editing?.revision||0)+1;setBusy(true);$('#form-error').textContent='';try{const rows=await request(editing?`?id=eq.${editing.id}&revision=eq.${editing.revision}`:'',editing?'PATCH':'POST',data);if(!rows.length)throw new Error('這筆資料剛被朋友修改了。請關閉後重開編輯，避免蓋掉新內容。');$('#editor').close()}catch(err){$('#form-error').textContent=err.message}finally{setBusy(false);await sync()}};
$('#remove').onclick=async()=>{if(!editing||busy||!confirm(`確定刪除「${editing.title}」？`))return;setBusy(true);try{const rows=await request(`?id=eq.${editing.id}&revision=eq.${editing.revision}`,'DELETE');if(!rows.length)throw new Error('這筆資料已被修改，請關閉後重新確認。');$('#editor').close()}catch(err){$('#form-error').textContent=err.message}finally{setBusy(false);await sync()}};
function showPerson(){$('#identity-button').textContent=person||'選擇姓名';$('#identity-button').setAttribute('aria-label','切換編輯者'+(person?' '+person:''))}
$('#identity-button').onclick=()=>$('#identity-dialog').showModal();
$('#identity-dialog').addEventListener('cancel',e=>{if(!person)e.preventDefault()});
document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{person=b.dataset.person;try{localStorage.setItem('japan_tsmc_person',person)}catch{}showPerson();$('#identity-dialog').close()});
showPerson();if(!person)$('#identity-dialog').showModal();
sync();setInterval(()=>{if(!document.hidden)sync()},10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
